# Generated by Django 3.0.1 on 2020-01-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_link', models.CharField(max_length=500)),
                ('item', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('base_price', models.CharField(max_length=100)),
            ],
        ),
    ]
