# Generated by Django 3.0.1 on 2020-01-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_ptmodel1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PtModel',
        ),
    ]
